name: Executable Spec (Gherkin)
description: 🙋 New Feature Provide a general summary of the issue here
title: '🙋 New Feature: Provide a general summary of the issue here'
body:
  - type: input
    attributes:
      label: 'Feature:'
  - type: checkboxes
    attributes:
      label: 'Background:'
      options:
        - label: 'Has Background'
  - type: input
    attributes:
      label: 'Scenario:'
  - type: input
    attributes:
      label: Given
  - type: input
    attributes:
      label: And
      placeholder: And
  - type: select
    id: example-count
    attributes:
      label: How many reproducible examples do you have?
      required: true
    options:
      - value: "1"
        label: "1"
      - value: "2"
        label: "2"
      - value: "3"
        label: "3"

{% for i in (1..3) %}
  - type: textarea
    id: example{{ i }}
    attributes:
      label: Example {{ i }}
      required: true
    conditional:
      equals:
        field: example-count
        value: "{{ i }}"
{% endfor %}
