name: Bug report
description: Template for bug reports
title: ðŸ™‹ [Feature Request:] Provide a general summary of the issue here
labels:
  - enhancement
body:
  - type: textarea
    id: id-expected-behavior
    attributes:
      label: ðŸ¤” Expected Behavior
      placeholder: Tell us how the feature should work
  - type: textarea
    id: id-current-behavior
    attributes:
      label: ðŸ˜¯ Current Behavior
      placeholder: Explain the difference from current behavior
  - type: textarea
    id: id-possible-solution
    attributes:
      label: ðŸ’ Possible Solution
      placeholder: >-
        Ideas how to implement this feature or a similar solution/workaround
        that already exists
  - type: textarea
    id: id-context
    attributes:
      label: ðŸ”¦ Context
      placeholder: How has this issue affected you? What are you trying to accomplish?
  - type: input
    id: id-example
    attributes:
      label: ðŸ’» Examples
      placeholder: Examples help us understand the requested feature better
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
